[build]
builder = "NIXPACKS"
buildCommand = "npx prisma generate && npm run build"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
